# The URL the site will be built for
base_url = "https://susonwaiba.github.io"

title = "Suson Waiba"
description = "Software developer writing quality software solutions"

author = "Suson Waiba"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", paginate_by = 5, sort_by = "date", paginate_reversed = false },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
long_title = "Suson Waiba - Software developer writing quality software solutions"
# Put all your custom variables here
